#!/usr/bin/env zsh
DIR="$( cd "$( dirname "$0" )" && pwd )"
cd $DIR

sudo rsync -vahP \
  ../dist/sites-enabled/* \
  pixelastic:/etc/nginx/sites-enabled

sudo rsync -vahP \
  ../dist/sites-available/* \
  pixelastic:/etc/nginx/sites-available

